// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBekZ1BDvs8wjhN0eMrPT2yJZvhHubdxpg',
    appId: '1:376601558991:web:7c792bd834cdcbb39c9cba',
    messagingSenderId: '376601558991',
    projectId: 'shoppinglist-ea438',
    authDomain: 'shoppinglist-ea438.firebaseapp.com',
    storageBucket: 'shoppinglist-ea438.appspot.com',
    measurementId: 'G-TDLGH9M7BE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlgv7cDmBZVxO0-VPB_91nbghszzpuWvY',
    appId: '1:376601558991:android:6150a1e6ddd3d9799c9cba',
    messagingSenderId: '376601558991',
    projectId: 'shoppinglist-ea438',
    storageBucket: 'shoppinglist-ea438.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSB4ONZBgxu-N_6V99cdC2T_xn7bHs9h0',
    appId: '1:376601558991:ios:d7795739886b9fd19c9cba',
    messagingSenderId: '376601558991',
    projectId: 'shoppinglist-ea438',
    storageBucket: 'shoppinglist-ea438.appspot.com',
    iosClientId:
        '376601558991-a9pa5kptu3ts3e7abgbci8l22ssic4oq.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
